// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN   MessageType = 0
	MessageType_MESSAGE_TYPE_SINGLE    MessageType = 1 // 私聊
	MessageType_MESSAGE_TYPE_COMMUNITY MessageType = 2 // 群聊
	MessageType_MESSAGE_TYPE_BROADCAST MessageType = 3 // 广播
	MessageType_MESSAGE_TYPE_HEARTBEAT MessageType = 4 // 心跳
	MessageType_MESSAGE_TYPE_ACK       MessageType = 5 // ACK
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_SINGLE",
		2: "MESSAGE_TYPE_COMMUNITY",
		3: "MESSAGE_TYPE_BROADCAST",
		4: "MESSAGE_TYPE_HEARTBEAT",
		5: "MESSAGE_TYPE_ACK",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN":   0,
		"MESSAGE_TYPE_SINGLE":    1,
		"MESSAGE_TYPE_COMMUNITY": 2,
		"MESSAGE_TYPE_BROADCAST": 3,
		"MESSAGE_TYPE_HEARTBEAT": 4,
		"MESSAGE_TYPE_ACK":       5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

// 媒体类型枚举
type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNKNOWN MediaType = 0
	MediaType_MEDIA_TYPE_TEXT    MediaType = 1 // 文字
	MediaType_MEDIA_TYPE_IMAGE   MediaType = 2 // 图片
	MediaType_MEDIA_TYPE_AUDIO   MediaType = 3 // 音频
	MediaType_MEDIA_TYPE_VIDEO   MediaType = 4 // 视频
	MediaType_MEDIA_TYPE_FILE    MediaType = 5 // 文件
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNKNOWN",
		1: "MEDIA_TYPE_TEXT",
		2: "MEDIA_TYPE_IMAGE",
		3: "MEDIA_TYPE_AUDIO",
		4: "MEDIA_TYPE_VIDEO",
		5: "MEDIA_TYPE_FILE",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNKNOWN": 0,
		"MEDIA_TYPE_TEXT":    1,
		"MEDIA_TYPE_IMAGE":   2,
		"MEDIA_TYPE_AUDIO":   3,
		"MEDIA_TYPE_VIDEO":   4,
		"MEDIA_TYPE_FILE":    5,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 消息请求
type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                            // 消息序号（可选，服务器可自动生成）
	FromId        int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`        // 发送者ID（必填）
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`  // 接收者ID（必填）
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=message.MessageType" json:"type,omitempty"` // 消息类型（必填）
	Media         MediaType              `protobuf:"varint,5,opt,name=media,proto3,enum=message.MediaType" json:"media,omitempty"` // 媒体类型（必填）
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                     // 消息内容（必填）
	Pic           string                 `protobuf:"bytes,7,opt,name=pic,proto3" json:"pic,omitempty"`                             // 图片URL（可选，当media=IMAGE时使用）
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`                             // 文件URL（可选，当media=FILE/VIDEO/AUDIO时使用）
	Desc          string                 `protobuf:"bytes,9,opt,name=desc,proto3" json:"desc,omitempty"`                           // 文件描述（可选）
	Amount        int32                  `protobuf:"varint,10,opt,name=amount,proto3" json:"amount,omitempty"`                     // 数据大小（可选，单位：字节）
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                // 时间戳（可选，服务器可自动生成）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *MessageRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *MessageRequest) GetMedia() MediaType {
	if x != nil {
		return x.Media
	}
	return MediaType_MEDIA_TYPE_UNKNOWN
}

func (x *MessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageRequest) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *MessageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MessageRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MessageRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MessageRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 消息响应
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                   // 消息序号（服务器分配）
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                           // 是否成功
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`          // 错误信息（失败时返回）
	LastAckSeq    int64                  `protobuf:"varint,4,opt,name=last_ack_seq,json=lastAckSeq,proto3" json:"last_ack_seq,omitempty"` // 最后确认的序号（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *MessageResponse) GetLastAckSeq() int64 {
	if x != nil {
		return x.LastAckSeq
	}
	return 0
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID（必填，用于标识连接）
	ServerId      int64                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器ID（可选，用于多服务器场景）
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                // 时间戳（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HeartbeatRequest) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"` // 是否存活
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ACK确认请求
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                           // 确认的消息序号（必填）
	FromId        int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`       // 发送ACK的用户ID（必填，接收方ID）
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 原始发送方ID（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AckRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *AckRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

// ACK确认响应
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`             // 是否成功
	AckSeq        int64                  `protobuf:"varint,2,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"` // 已确认的最大序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetAckSeq() int64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\x0eMessageRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.message.MessageTypeR\x04type\x12(\n" +
	"\x05media\x18\x05 \x01(\x0e2\x12.message.MediaTypeR\x05media\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x10\n" +
	"\x03pic\x18\a \x01(\tR\x03pic\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x12\n" +
	"\x04desc\x18\t \x01(\tR\x04desc\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x05R\x06amount\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"|\n" +
	"\x0fMessageResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12 \n" +
	"\flast_ack_seq\x18\x04 \x01(\x03R\n" +
	"lastAckSeq\"\x82\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x03R\bserverId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"c\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"T\n" +
	"\n" +
	"AckRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"@\n" +
	"\vAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aack_seq\x18\x02 \x01(\x03R\x06ackSeq*\xaa\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13MESSAGE_TYPE_SINGLE\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_COMMUNITY\x10\x02\x12\x1a\n" +
	"\x16MESSAGE_TYPE_BROADCAST\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\x04\x12\x14\n" +
	"\x10MESSAGE_TYPE_ACK\x10\x05*\x8f\x01\n" +
	"\tMediaType\x12\x16\n" +
	"\x12MEDIA_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fMEDIA_TYPE_TEXT\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x02\x12\x14\n" +
	"\x10MEDIA_TYPE_AUDIO\x10\x03\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x04\x12\x13\n" +
	"\x0fMEDIA_TYPE_FILE\x10\x052\xa0\x02\n" +
	"\x0eMessageService\x12@\n" +
	"\vSendMessage\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponse\x12G\n" +
	"\x0eStreamMessages\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponse(\x010\x01\x12B\n" +
	"\tHeartbeat\x12\x19.message.HeartbeatRequest\x1a\x1a.message.HeartbeatResponse\x12?\n" +
	"\x12AcknowledgeMessage\x12\x13.message.AckRequest\x1a\x14.message.AckResponseB\x19Z\x17MyChat/protobuf/messageb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_message_proto_goTypes = []any{
	(MessageType)(0),              // 0: message.MessageType
	(MediaType)(0),                // 1: message.MediaType
	(*MessageRequest)(nil),        // 2: message.MessageRequest
	(*MessageResponse)(nil),       // 3: message.MessageResponse
	(*HeartbeatRequest)(nil),      // 4: message.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: message.HeartbeatResponse
	(*AckRequest)(nil),            // 6: message.AckRequest
	(*AckResponse)(nil),           // 7: message.AckResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.MessageRequest.type:type_name -> message.MessageType
	1, // 1: message.MessageRequest.media:type_name -> message.MediaType
	8, // 2: message.MessageRequest.timestamp:type_name -> google.protobuf.Timestamp
	8, // 3: message.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	8, // 4: message.HeartbeatResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // 5: message.MessageService.SendMessage:input_type -> message.MessageRequest
	2, // 6: message.MessageService.StreamMessages:input_type -> message.MessageRequest
	4, // 7: message.MessageService.Heartbeat:input_type -> message.HeartbeatRequest
	6, // 8: message.MessageService.AcknowledgeMessage:input_type -> message.AckRequest
	3, // 9: message.MessageService.SendMessage:output_type -> message.MessageResponse
	3, // 10: message.MessageService.StreamMessages:output_type -> message.MessageResponse
	5, // 11: message.MessageService.Heartbeat:output_type -> message.HeartbeatResponse
	7, // 12: message.MessageService.AcknowledgeMessage:output_type -> message.AckResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
